spring:
  application:
    name: processing

  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}

  mongodb:
      uri: ${SPRING_DATA_MONGODB_URI:mongodb://localhost:27017/processing}

app:
  rabbitmq:
    exchange: ${RABBITMQ_EXCHANGE:petitions-exchange}
    queue: ${RABBITMQ_QUEUE:petitions-queue}
    routing-key: ${RABBITMQ_ROUTING_KEY:petition.created}
